import type { Template } from '@/types';

export const arrowMinimal: Template = {
    id: 'arrow-minimal',
    metadata: {
        name: 'Arrow Minimal',
        category: 'minimal',
        colorSupport: 1,
        description: 'Diseño minimalista con línea decorativa y flecha direccional',
        tags: ['minimal', 'clean', 'arrow', 'simple']
    },

    viewport: {
        width: 1080,
        height: 1350,
        safeMargin: 60,
    },

    background: {
        type: 'solid',
        colorVar: 'brand_primary',
    },

    design_elements: [
        // Horizontal arrow line (decorative)
        {
            id: 'arrow-line',
            type: 'line',
            x1: 108,
            y1: 1240,
            x2: 972,
            y2: 1240,
            stroke: '#000000',
            strokeWidth: 3,
            opacity: 1,
            zIndex: 2,
        },
        // Arrow head
        {
            id: 'arrow-head',
            type: 'svg',
            svgCode: `<svg viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                <path d="M12,10 L6,6 L6,14 Z" fill="currentColor"/>
            </svg>`,
            x: 960,
            y: 1230,
            width: 20,
            height: 20,
            tinted: true,
            colorVar: 'brand_secondary',
            rotation: 0,
            opacity: 1,
            zIndex: 3,
        },
        // Small accent rectangle (top right)
        {
            id: 'accent-rect',
            type: 'rectangle',
            x: 950,
            y: 116,
            width: 63,
            height: 22,
            fill: 'brand_secondary',
            borderRadius: 0,
            opacity: 1,
            zIndex: 2,
        },
    ],

    text_slots: {
        slide_number: {
            enabled: true,
            x: 108,
            y: 80,
            width: 100,
            height: 60,
            fontFamily: 'Inter',
            fontSize: 48,
            fontWeight: 700,
            color: '#000000',
            textAlign: 'left',
            verticalAlign: 'top',
            lineHeight: 1,
            letterSpacing: -1,
            textTransform: 'none',
            numberFormat: '01',
            autoFit: false,
            minFontSize: 32,
            zIndex: 8,
        },

        label: {
            enabled: false,
            x: 0,
            y: 0,
            width: 0,
            height: 0,
            fontFamily: 'Inter',
            fontSize: 16,
            fontWeight: 400,
            color: '#000000',
            textAlign: 'left',
            verticalAlign: 'top',
            lineHeight: 1,
            letterSpacing: 0,
            textTransform: 'none',
            autoFit: false,
            zIndex: 0,
        },

        tag: {
            enabled: true,
            x: 108,
            y: 180,
            width: 800,
            height: 40,
            fontFamily: 'Inter',
            fontSize: 20,
            fontWeight: 500,
            color: '#000000',
            textAlign: 'left',
            verticalAlign: 'top',
            lineHeight: 1.3,
            letterSpacing: 0.5,
            textTransform: 'uppercase',
            autoFit: true,
            minFontSize: 14,
            maxLines: 1,
            zIndex: 8,
        },

        title: {
            enabled: true,
            x: 108,
            y: 250,
            width: 864,
            height: 550,
            fontFamily: 'Inter',
            fontSize: 96,
            fontWeight: 700,
            color: '#000000',
            textAlign: 'left',
            verticalAlign: 'top',
            lineHeight: 1.05,
            letterSpacing: -2,
            textTransform: 'none',
            autoFit: true,
            minFontSize: 48,
            maxLines: 5,
            zIndex: 9,

            emphasisStyle: {
                fontWeight: 900,
                color: '#000000',
            },
        },

        body: {
            enabled: true,
            x: 108,
            y: 850,
            width: 864,
            height: 320,
            fontFamily: 'Inter',
            fontSize: 40,
            fontWeight: 400,
            color: '#000000',
            textAlign: 'left',
            verticalAlign: 'top',
            lineHeight: 1.4,
            letterSpacing: 0,
            textTransform: 'none',
            autoFit: true,
            minFontSize: 24,
            maxLines: 5,
            zIndex: 8,

            emphasisStyle: {
                fontWeight: 700,
                color: '#000000',
            },
        },

        cta_text: {
            enabled: false,
            x: 0,
            y: 0,
            width: 0,
            height: 0,
            fontFamily: 'Inter',
            fontSize: 16,
            fontWeight: 400,
            color: '#000000',
            textAlign: 'left',
            verticalAlign: 'top',
            lineHeight: 1,
            letterSpacing: 0,
            textTransform: 'none',
            autoFit: false,
            zIndex: 0,
        },
    },

    global_slots: {
        logo: {
            enabled: false,
            x: 0,
            y: 0,
            width: 0,
            height: 0,
            fit: 'contain',
            borderRadius: 0,
            opacity: 0,
            zIndex: 10,
        },

        author: {
            enabled: true,
            x: 108,
            y: 1280,
            width: 400,
            height: 30,
            fontFamily: 'Inter',
            fontSize: 18,
            fontWeight: 600,
            color: '#000000',
            textAlign: 'left',
            verticalAlign: 'middle',
            lineHeight: 1,
            letterSpacing: 0,
            prefix: '@',
            opacity: 0.8,
            zIndex: 10,
        },

        website: {
            enabled: false,
            x: 0,
            y: 0,
            width: 0,
            height: 0,
            fontFamily: 'Inter',
            fontSize: 16,
            fontWeight: 400,
            color: '#000000',
            textAlign: 'left',
            verticalAlign: 'middle',
            lineHeight: 1,
            letterSpacing: 0,
            opacity: 0,
            zIndex: 10,
        },
    },

    variations: {
        hook: {
            background: {
                type: 'solid',
                colorVar: 'brand_primary',
            },
            design_elements: [
                {
                    id: 'hook-arrow-line',
                    type: 'line',
                    x1: 108,
                    y1: 750,
                    x2: 972,
                    y2: 750,
                    stroke: '#000000',
                    strokeWidth: 3,
                    opacity: 1,
                    zIndex: 2,
                },
                {
                    id: 'hook-arrow-head',
                    type: 'svg',
                    svgCode: `<svg viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                        <path d="M12,10 L6,6 L6,14 Z" fill="currentColor"/>
                    </svg>`,
                    x: 960,
                    y: 740,
                    width: 20,
                    height: 20,
                    tinted: true,
                    colorVar: 'brand_secondary',
                    rotation: 0,
                    opacity: 1,
                    zIndex: 3,
                },
            ],
            text_slots: {
                slide_number: {
                    enabled: false,
                    x: 0,
                    y: 0,
                    width: 0,
                    height: 0,
                    fontFamily: 'Inter',
                    fontSize: 16,
                    fontWeight: 400,
                    color: '#000000',
                    textAlign: 'left',
                    verticalAlign: 'top',
                    lineHeight: 1,
                    letterSpacing: 0,
                    textTransform: 'none',
                    autoFit: false,
                    zIndex: 0,
                },
                label: {
                    enabled: false,
                    x: 0,
                    y: 0,
                    width: 0,
                    height: 0,
                    fontFamily: 'Inter',
                    fontSize: 16,
                    fontWeight: 400,
                    color: '#000000',
                    textAlign: 'left',
                    verticalAlign: 'top',
                    lineHeight: 1,
                    letterSpacing: 0,
                    textTransform: 'none',
                    autoFit: false,
                    zIndex: 0,
                },
                tag: {
                    enabled: true,
                    fontSize: 24,
                    textAlign: 'center',
                    x: 108,
                    y: 300,
                    width: 864,
                    height: 40,
                    fontFamily: 'Inter',
                    fontWeight: 500,
                    color: '#000000',
                    verticalAlign: 'top',
                    lineHeight: 1.3,
                    letterSpacing: 0.5,
                    textTransform: 'uppercase',
                    autoFit: true,
                    minFontSize: 14,
                    zIndex: 8,

                    emphasisStyle: {
                        fontWeight: 700,
                        color: '#000000',
                    },
                },
                title: {
                    enabled: true,
                    fontSize: 110,
                    textAlign: 'center',
                    verticalAlign: 'middle',
                    x: 108,
                    y: 380,
                    width: 864,
                    height: 350,
                    color: '#000000',
                    fontFamily: 'Inter',
                    fontWeight: 700,
                    lineHeight: 1.05,
                    letterSpacing: -2,
                    textTransform: 'none',
                    autoFit: true,
                    minFontSize: 48,
                    zIndex: 9,

                    emphasisStyle: {
                        fontWeight: 900,
                        color: '#000000',
                    },
                },
                body: {
                    enabled: false,
                    x: 0,
                    y: 0,
                    width: 0,
                    height: 0,
                    fontFamily: 'Inter',
                    fontSize: 16,
                    fontWeight: 400,
                    color: '#000000',
                    textAlign: 'left',
                    verticalAlign: 'top',
                    lineHeight: 1,
                    letterSpacing: 0,
                    textTransform: 'none',
                    autoFit: false,
                    zIndex: 0,
                },
            },
        },

        cta: {
            background: {
                type: 'solid',
                colorVar: 'brand_primary',
            },
            design_elements: [
                {
                    id: 'cta-arrow-line',
                    type: 'line',
                    x1: 108,
                    y1: 900,
                    x2: 972,
                    y2: 900,
                    stroke: '#000000',
                    strokeWidth: 3,
                    opacity: 1,
                    zIndex: 2,
                },
                {
                    id: 'cta-arrow-head',
                    type: 'svg',
                    svgCode: `<svg viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                        <path d="M12,10 L6,6 L6,14 Z" fill="currentColor"/>
                    </svg>`,
                    x: 960,
                    y: 890,
                    width: 20,
                    height: 20,
                    tinted: true,
                    colorVar: 'brand_secondary',
                    rotation: 0,
                    opacity: 1,
                    zIndex: 3,
                },
            ],
            text_slots: {
                slide_number: {
                    enabled: false,
                    x: 0,
                    y: 0,
                    width: 0,
                    height: 0,
                    fontFamily: 'Inter',
                    fontSize: 16,
                    fontWeight: 400,
                    color: '#000000',
                    textAlign: 'left',
                    verticalAlign: 'top',
                    lineHeight: 1,
                    letterSpacing: 0,
                    textTransform: 'none',
                    autoFit: false,
                    zIndex: 0,
                },
                label: {
                    enabled: false,
                    x: 0,
                    y: 0,
                    width: 0,
                    height: 0,
                    fontFamily: 'Inter',
                    fontSize: 16,
                    fontWeight: 400,
                    color: '#000000',
                    textAlign: 'left',
                    verticalAlign: 'top',
                    lineHeight: 1,
                    letterSpacing: 0,
                    textTransform: 'none',
                    autoFit: false,
                    zIndex: 0,
                },
                tag: {
                    enabled: false,
                    x: 0,
                    y: 0,
                    width: 0,
                    height: 0,
                    fontFamily: 'Inter',
                    fontSize: 16,
                    fontWeight: 400,
                    color: '#000000',
                    textAlign: 'left',
                    verticalAlign: 'top',
                    lineHeight: 1,
                    letterSpacing: 0,
                    textTransform: 'none',
                    autoFit: false,
                    zIndex: 0,
                },
                title: {
                    enabled: true,
                    fontSize: 80,
                    textAlign: 'center',
                    x: 108,
                    y: 400,
                    width: 864,
                    height: 300,
                    fontFamily: 'Inter',
                    fontWeight: 700,
                    color: '#000000',
                    verticalAlign: 'middle',
                    lineHeight: 1.05,
                    letterSpacing: -2,
                    textTransform: 'none',
                    autoFit: true,
                    minFontSize: 48,
                    zIndex: 9,

                    emphasisStyle: {
                        fontWeight: 900,
                        color: '#000000',
                    },
                },
                body: {
                    enabled: true,
                    fontSize: 32,
                    textAlign: 'center',
                    x: 108,
                    y: 950,
                    width: 864,
                    height: 80,
                    fontFamily: 'Inter',
                    fontWeight: 600,
                    color: '#000000',
                    verticalAlign: 'middle',
                    lineHeight: 1.3,
                    letterSpacing: 0.5,
                    textTransform: 'none',
                    autoFit: true,
                    minFontSize: 24,
                    zIndex: 9,
                },
                cta_text: {
                    enabled: false,
                    x: 0,
                    y: 0,
                    width: 0,
                    height: 0,
                    fontFamily: 'Inter',
                    fontSize: 16,
                    fontWeight: 400,
                    color: '#000000',
                    textAlign: 'left',
                    verticalAlign: 'top',
                    lineHeight: 1,
                    letterSpacing: 0,
                    textTransform: 'none',
                    autoFit: false,
                    zIndex: 0,
                },
            },
        },
    },
};
